# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
             users:
               admin: {password: $2y$15$unKPYG7tbexkZZJuAuznreJsw.M91Vt2lzvs9/5WrRsf58PDUFQUK,
                roles: ["ROLE_ADMIN"]}
               god:
                password: $2y$15$AF/jLTa9mE1p2aal4mWNKOi09OAy8FgTR3X9OOJIwNqTfpbzr7uPm,

                roles: ["ROLE_SUPER_ADMIN", "ROLE_ADMIN"]
        author_provider:
          entity:
             class: AppBundle:Author
             property: email

    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: bcrypt
          cost: 15
        AppBundle\Entity\Author:
          algorithm: bcrypt

    role-hierarchy:
      ROLE_SUPER_ADMIN: ROLE_ALLOWED_TO_SWITCH

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
          pattern: ^/admin/login$
          anonymous: ~

        admin_firwall:
          pattern: ^/admin
          provider: in_memory
          form_login:
            login_path: admin_login
            check_path: admin_login_check
            default_target_path: admin_home
          logout:
              path: admin_logout
              target: homepage


        main:
          anonymous: true
          pattern: ^/
          provider: author_provider
          form_login:
              login_path: author_provider
              check_path: author_login_check
              default_target_path: homepage
          logout:
              path: author_logout
              target: homepage
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    access-control:
      - {path: ^/admin/secure, roles: ROLE_SUPER_ADMIN}
